server:
  port: 8002
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.160.105:3306/cloud2020?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities. #所有Entity别名类所在包


eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetchRegistry: true
  instance:
    instance-id: payment8002
    #访问地址显示IP地址
    prefer-ip-address: true