server:
  port: 80
spring:
  application:
    name: cloud-consumer-hystrix-order

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetchRegistry: true

#设置feign客户端超时时间（OpenFeign默认支持ribbog)
ribbon:
  #指的是建立链接所用的时间，适用于网络状况正常的情况下，两端连接所有的时间
  ReadTimeout: 20000
  #指的是建立连接后服务器读取到可用资源所用的时间
  ConnectTimeout: 20000
feign:
  hystrix:
    enabled: true
